version: "3"

services:
  node:
    container_name: oab-mentoring-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_ACCESS_TOKEN=${TELEGRAM_BOT_ACCESS_TOKEN}
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
  
  postgres:
    container_name: database
    image: postgres:12
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "oab_mentoring_bot"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
