version: '3'
services:

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data-dev:/data/postgres"
    env_file:
      - docker-compose.dev.postgres.env

  redis:
    ports:
      - "6379:6379"

  bot:
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src"
    env_file:
      - docker-compose.dev.bot.env
    command: npm run dev

  admin-studio:
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - docker-compose.dev.postgres.env
    ports:
      - "5555:5555"
    depends_on:
      - postgres

volumes:
  postgres-data-dev: