version: '3'
services:

  postgres:
    volumes:
      - "postgres-data:/data/postgres"
    env_file:
      - docker-compose.prod.postgres.env

  bot:
    ports:
      - "8080:8080"
    env_file:
      - docker-compose.prod.bot.env

  admin:
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - docker-compose.prod.postgres.env
    ports:
      - "5555:5555"
    depends_on:
      - postgres

volumes:
  postgres-data: